<?php


/**
 * This class adds structure of 'alsignup_newsletter_adverts' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Aug 11 18:37:08 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.alSignupPlugin.lib.model.map
 */
class AlSignupNewsletterAdsMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.alSignupPlugin.lib.model.map.AlSignupNewsletterAdsMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AlSignupNewsletterAdsPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AlSignupNewsletterAdsPeer::TABLE_NAME);
		$tMap->setPhpName('AlSignupNewsletterAds');
		$tMap->setClassname('AlSignupNewsletterAds');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('NEWSLETTER_ADVERTS_ID', 'NewsletterAdvertsId', 'INTEGER', true, null);

		$tMap->addColumn('ADVERTISED', 'Advertised', 'VARCHAR', true, 30);

	} // doBuild()

} // AlSignupNewsletterAdsMapBuilder
