<?php


/**
 * This class adds structure of 'alsignup_newsletter_signups' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Aug 11 18:37:08 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.alSignupPlugin.lib.model.map
 */
class AlSignupNewsletterSignupMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.alSignupPlugin.lib.model.map.AlSignupNewsletterSignupMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AlSignupNewsletterSignupPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AlSignupNewsletterSignupPeer::TABLE_NAME);
		$tMap->setPhpName('AlSignupNewsletterSignup');
		$tMap->setClassname('AlSignupNewsletterSignup');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('FIRST_NAME', 'FirstName', 'VARCHAR', true, 20);

		$tMap->addColumn('SURNAME', 'Surname', 'VARCHAR', true, 20);

		$tMap->addColumn('EMAIL', 'Email', 'VARCHAR', true, 100);

		$tMap->addColumn('ACTIVATION_KEY', 'ActivationKey', 'VARCHAR', true, 100);

		$tMap->addColumn('ACTIVATED', 'Activated', 'BOOLEAN', true, null);

		$tMap->addForeignKey('NEWSLETTER_ADVERTS_ID', 'NewsletterAdvertsId', 'INTEGER', 'alsignup_newsletter_adverts', 'NEWSLETTER_ADVERTS_ID', true, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', true, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', true, null);

	} // doBuild()

} // AlSignupNewsletterSignupMapBuilder
