<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/09/04 14:28:22

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:dbname=milkshake;host=localhost',
  'username' => 'root',
  'password' => 'Panties69',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
