<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/09/04 14:28:23
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
  'mod_'.strtolower($moduleName).'_mailer_deliver' => true,
  'mod_'.strtolower($moduleName).'_mailer_subject' => 'Milkshake Newsletter',
  'mod_'.strtolower($moduleName).'_mailer_from_name' => 'Tim',
  'mod_'.strtolower($moduleName).'_mailer_from_email' => 'no-reply@milkshake',
));
