generator:
  class: sfPropelGenerator
  param:
    model_class:           Milkshake
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          milkshake
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:
        display: [name, image_url, _thumb, calories, url_slug, milkshake_flavor_list]
      new:     ~
