default:
  http_metas:
    content-type: text/html

  metas:
    title:        Milkshake Administration
    robots:       noindex, nofollow
    description:  
    keywords:     
    language:     en

  stylesheets:    [smoothness/jquery-ui-1.7.1.custom.css]

  javascripts:    [jquery-1.3.2.min.js, jquery-ui.1.7.1.custom.min.js, tiny_mce/tiny_mce.js]

  has_layout:     on
  layout:         layout
